# Generated by Django 4.2.5 on 2025-02-10 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('limma', '0011_remove_customer_address_remove_customer_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='name',
        ),
    ]
