# Generated by Django 4.2.5 on 2025-02-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limma', '0013_alter_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
